server:
  port: 8081

spring:
  # ----------------------------------------------------
  # 1. CONFIGURAÇÃO DE BANCO DE DADOS
  # ----------------------------------------------------
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${AGENDAMENTO_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
    initialization-mode: never
    platform: postgresql
    hikari:
      max-lifetime: 1800000
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
      hbm2ddl:
        import_files:
          classpath: import.sql
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

  # ----------------------------------------------------
  # 2. SERIALIZAÇÃO E JACKSON
  # ----------------------------------------------------
  jackson:
    default-property-inclusion: non_null

  # ----------------------------------------------------
  # 3. CONFIGURAÇÃO KAFKA (PRODUTOR E CONSUMIDOR)
  # ----------------------------------------------------
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: agendamento-medicos-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.postechfiap.meuhospital.contracts.events
        spring.json.value.default.type: com.postechfiap.meuhospital.contracts.events.MedicoEvent
    producer:
      client-id: ms-agendamento-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.properties.enabled: false

# ----------------------------------------------------
# CONFIGURAÇÕES DE DOMÍNIO E SEGURANÇA
# ----------------------------------------------------
app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION_MS}

  auth-service-url: http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}/usuarios
  internal-secret: ${INTERNAL_SECRET}

  kafka:
    topic-medico-update: medico-events
    topic-notificacao: notificacao-events

# ----------------------------------------------------
# DOCUMENTAÇÃO E LOGS
# ----------------------------------------------------
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: INFO
    com.postechfiap: DEBUG